#!/usr/bin/env bash
# codemap stitcher — run ALL THREE edge families in one command.
#
# Why this file exists: derive / infra / datastore / reconcile / emit were five separate CLIs with
# no runner, so a pipeline was a sequence a human retyped. The failure that produced was silent and
# total — the physical layer (infra -> reconcile -> emit --reconciled) was fully implemented and
# contributed ZERO edges to the served map, because two of the five commands were simply never run
# and nothing anywhere reported their absence. A missing family is now a loud failure, not an
# invisible one.
#
#   ./stitcher/run-pipeline.sh --config config/codemap.toml --out-dir build/
#
# Options:
#   --live <topology.json>   reconcile static IaC against a live cloud snapshot (Tier B/C).
#                            Omitted => static-only reconcile, which still yields every
#                            IaC-declared physical edge.
#   --allow-ungrounded       proceed when [stitcher] ground = true but the oracle is unavailable.
#                            Edges are then stamped grounded: false. Deliberate, never a default.
#   --skip-ground            do not attempt grounding at all (implies --allow-ungrounded).
#   --vault <dir>            ALSO generate the physical-layer node pages, merge the patches into
#                            that vault, and give every remaining off-vault edge target a stub
#                            page (steps 7-9). Omitted => the pipeline stops after emit and
#                            prints the three remaining commands, as before.
#   --strict                 pass --strict to the write door (resolved edges only; see its
#                            docstring for why `dynamic` cannot pass and how to exclude it).
#   --skip-stubs             do not generate stub pages for off-vault edge targets (step 9).
#                            Those edges then stay dead ends: `xedges --from X` returns them and
#                            `query <target>` answers "not found". Deliberate, never a default —
#                            see the note on step 9 below.
#   --env <name>             render IaC names for [cloud.environments.<name>]: its `tfvars` table
#                            supplies values for variables that have no default. Omitted => no
#                            var-file is read and such variables stay (unset:var.<name>).
#
# Writes candidates/infra/datastore/reconciled/grounding/patches + service_inventory into --out-dir.
#
# WITHOUT --vault it does not touch a vault at all. That separation was deliberate, and it also
# meant no script in the pack ever performed the merge -- so the physical layer was extracted,
# emitted, and never landed, because the home pages its edges need are generated by
# tools/deployed.py and the write door's --dirs default did not include that directory. --vault
# closes that path: one documented invocation now takes IaC to served edges.
#
# STEP 9 EXISTS FOR THE SAME REASON STEP 7 DOES, and it was missed the same way. tools/stubs.py
# was in the package, tested, and invoked by nothing: after the documented invocation 151 of 208
# served runtime edges still terminated on a label with no page, and the only thing that reported
# the condition was a tool a human had to know to run. It is step 9 rather than step 7.5 because
# it reads the SERVED vault (tools/stubs.py takes only --vault and walks the pages' cross_service
# frontmatter), so it can only see edges the write door has already landed.
#
# It also runs when the write door FAILS. The door exits non-zero on a real workspace by design
# (an unresolved home page, a strict rejection), and with `set -e` that aborted the script -- so
# wiring stubs in as a plain trailing command would have left it unreached in exactly the case
# the pack documents as normal. The door's exit code is captured, step 9 runs, and the script
# still exits non-zero with the failing step NAMED, so the exit stays attributable to one step.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG=""; OUT_DIR="build"; LIVE=""; ALLOW_UNGROUNDED=0; SKIP_GROUND=0
VAULT=""; STRICT=0; SKIP_STUBS=0; ENV_NAME=""
while [ $# -gt 0 ]; do
  case "$1" in
    --config) CONFIG="$2"; shift 2;;
    --out-dir) OUT_DIR="$2"; shift 2;;
    --live) LIVE="$2"; shift 2;;
    --allow-ungrounded) ALLOW_UNGROUNDED=1; shift;;
    --skip-ground) SKIP_GROUND=1; ALLOW_UNGROUNDED=1; shift;;
    --vault) VAULT="$2"; shift 2;;
    --strict) STRICT=1; shift;;
    --skip-stubs) SKIP_STUBS=1; shift;;
    --env) ENV_NAME="$2"; shift 2;;
    -h|--help) sed -n '2,40p' "$0"; exit 0;;
    *) echo "unknown option: $1" >&2; exit 64;;
  esac
done
[ -n "$CONFIG" ] || { echo "--config is required" >&2; exit 64; }
[ -f "$CONFIG" ] || { echo "config not found: $CONFIG" >&2; exit 66; }
mkdir -p "$OUT_DIR"
PY="${PYTHON:-python3}"

step(){ printf '\n=== %s ===\n' "$1" >&2; }

step "1/9 derive — logical layer (call sites)"
"$PY" "$HERE/derive.py" --config "$CONFIG" --out "$OUT_DIR/candidates.json"

step "2/9 infra — physical layer (static IaC)${ENV_NAME:+ · env=$ENV_NAME}"
ENV_ARGS=()
[ -n "$ENV_NAME" ] && ENV_ARGS=(--env "$ENV_NAME")
"$PY" "$HERE/infra.py" --config "$CONFIG" --out "$OUT_DIR/infra.json" "${ENV_ARGS[@]}"

step "3/9 datastore — shared-datastore layer"
"$PY" "$HERE/datastore.py" --config "$CONFIG" --infra "$OUT_DIR/infra.json" \
      --out "$OUT_DIR/datastore_edges.json"

step "4/9 reconcile — declared ${LIVE:+⋈ live}"
if [ -n "$LIVE" ]; then
  "$PY" "$HERE/reconcile.py" --static "$OUT_DIR/infra.json" --live "$LIVE" \
        --out "$OUT_DIR/reconciled.json"
else
  "$PY" "$HERE/reconcile.py" --static "$OUT_DIR/infra.json" --out "$OUT_DIR/reconciled.json"
fi

GROUND_ARGS=()
if [ "$SKIP_GROUND" -eq 0 ]; then
  step "5/9 ground — LSP oracle (false-positive control)"
  WORKSPACE="$("$PY" - "$CONFIG" <<'EOF'
import sys, pathlib
try: import tomllib
except ModuleNotFoundError: import tomli as tomllib
print(tomllib.loads(pathlib.Path(sys.argv[1]).read_text())["codemap"]["workspace"])
EOF
)"
  if "$PY" "$HERE/ground.py" --project "$WORKSPACE" --edges "$OUT_DIR/candidates.json" \
        --out "$OUT_DIR/grounding.json"; then
    GROUND_ARGS=(--grounding "$OUT_DIR/grounding.json")
  else
    echo "grounding did not succeed — see $OUT_DIR/grounding.json (_meta.ok=false)." >&2
    if [ "$ALLOW_UNGROUNDED" -eq 1 ]; then
      echo "continuing because --allow-ungrounded was given; edges will be grounded: false" >&2
      GROUND_ARGS=(--grounding "$OUT_DIR/grounding.json" --allow-ungrounded)
    else
      echo "STOPPING. Emitting ungrounded edges while the config asks for grounding would" >&2
      echo "publish unvalidated edges that look validated. Re-run with --allow-ungrounded" >&2
      echo "to do it deliberately, or install the oracle." >&2
      exit 3
    fi
  fi
else
  step "5/9 ground — SKIPPED (--skip-ground)"
  GROUND_ARGS=(--allow-ungrounded)
fi

step "6/9 emit — all three families -> cross_service patches"
"$PY" "$HERE/emit.py" --config "$CONFIG" \
      --edges "$OUT_DIR/candidates.json" \
      --datastore "$OUT_DIR/datastore_edges.json" \
      --reconciled "$OUT_DIR/reconciled.json" \
      "${GROUND_ARGS[@]}" \
      --out "$OUT_DIR/patches.json"

# A family that produced nothing is reported here rather than being noticed months later.
"$PY" - "$OUT_DIR/patches.json" <<'EOF'
import collections, json, pathlib, sys
patches = json.loads(pathlib.Path(sys.argv[1]).read_text())
by = collections.Counter(o["type"] for v in patches.values() for o in v)
LOGICAL  = {"http-call", "data-store", "mcp-fanout", "dynamic"}
PHYSICAL = {"invokes", "subscribes-to", "publishes-to", "deploy-env", "runs-as", "in-dataset",
            "reads-from", "dns-resolves-to", "domain-maps-to", "part-of-network",
            "firewall-allows", "routes-to", "fronted-by", "reads-secret", "triggers"}
fam = {"logical": sum(by[k] for k in LOGICAL),
       "physical": sum(by[k] for k in PHYSICAL),
       "shares-datastore": by["shares-datastore"]}
print("\n--- family coverage ---", file=sys.stderr)
for k, v in fam.items():
    print(f"  {k:18s} {v}", file=sys.stderr)
empty = [k for k, v in fam.items() if v == 0]
if empty:
    print(f"  WARNING: {', '.join(empty)} produced NO edges. Either this workspace genuinely has "
          f"none, or that extractor is not reaching its inputs — check before publishing.",
          file=sys.stderr)
EOF
echo "" >&2
if [ -z "$VAULT" ]; then
  echo "patches written to $OUT_DIR/patches.json. NOTHING IS SERVED YET -- run:" >&2
  echo "  $PY $HERE/../tools/deployed.py --vault <vault> --inventory $OUT_DIR/service_inventory.json \\" >&2
  echo "        --patches $OUT_DIR/patches.json --apply" >&2
  echo "  $PY $HERE/write_door.py --config $CONFIG --patches $OUT_DIR/patches.json --apply" >&2
  echo "  $PY $HERE/../tools/stubs.py --vault <vault> --apply" >&2
  echo "Or re-run this script with --vault <vault> to do all three. Physical edges CANNOT land" >&2
  echo "without the first command: their home pages are the node pages it generates. Without the" >&2
  echo "third, every edge whose target has no page stays a dead end -- measured at 151 of 208" >&2
  echo "served edges on the reference workspace, reported by nothing." >&2
  exit 0
fi

[ -d "$VAULT" ] || { echo "--vault is not a directory: $VAULT" >&2; exit 66; }

step "7/9 deployed — physical-layer node pages (home pages for the physical edges)"
"$PY" "$HERE/../tools/deployed.py" --vault "$VAULT" \
      --inventory "$OUT_DIR/service_inventory.json" \
      --patches "$OUT_DIR/patches.json" --apply

step "8/9 write door — merge every family into the vault"
STRICT_ARGS=()
[ "$STRICT" -eq 1 ] && STRICT_ARGS=(--strict --exclude-type dynamic)
# The door's failure is EXPECTED on a real workspace (unresolved home page, strict rejection), and
# it must not skip step 9 -- see the note at the top of this file. Captured, not swallowed: the
# script's own exit code below is the door's, with the step named.
set +e
"$PY" "$HERE/write_door.py" --config "$CONFIG" --patches "$OUT_DIR/patches.json" \
      --apply --update-manifest "${STRICT_ARGS[@]}"
DOOR_RC=$?
set -e
[ "$DOOR_RC" -ne 0 ] && echo "write door exited $DOOR_RC (see its report above)" >&2

STUB_RC=0
if [ "$SKIP_STUBS" -eq 0 ]; then
  step "9/9 stubs — a page for every off-vault edge target (kills the dead ends)"
  set +e
  "$PY" "$HERE/../tools/stubs.py" --vault "$VAULT" --apply
  STUB_RC=$?
  set -e
  [ "$STUB_RC" -ne 0 ] && echo "stubs exited $STUB_RC (see its report above)" >&2
else
  step "9/9 stubs — SKIPPED (--skip-stubs); edges with no target page stay dead ends"
fi

echo "" >&2
echo "merged into $VAULT. Verify what is actually served:" >&2
echo "  bin/fmg -w $VAULT xedges -f json   # every runtime edge, by type" >&2
echo "  $PY $HERE/../tools/lint.py  --vault $VAULT" >&2
echo "  $PY $HERE/../tools/drift.py --vault $VAULT --config $CONFIG" >&2

# One exit code, one named cause. Two steps can fail here and the code alone cannot say which,
# so the cause is printed rather than left to be inferred from a number.
if [ "$DOOR_RC" -ne 0 ]; then
  echo "EXIT $DOOR_RC from step 8/9 (write door)." >&2
  exit "$DOOR_RC"
fi
if [ "$STUB_RC" -ne 0 ]; then
  echo "EXIT $STUB_RC from step 9/9 (stubs)." >&2
  exit "$STUB_RC"
fi
